repos:
  - repo: local
    hooks:
      - id: check-version
        name: Check version
        entry: deno run --allow-read script/check_version.ts
        language: system
        files: Makefile\.[\w-]+
